version: '1.1'

services:
    # PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - htl-kahoot-network
        image: cloudsigma.com/php
        restart: unless-stopped
        links:
            - db
        dns:
          - 8.8.8.8
          - 8.8.4.4
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: htl-kahoot
            DB_USERNAME: postgres
            DB_PASSWORD: password
            REDIS_HOST: redis
            REDIS_PORT: 6379
        working_dir: /var/www/html/
        volumes:
            - ./:/var/www/html/
            - ./php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini

    # Nginx Service
    webserver:
        image: nginx:alpine
        restart: unless-stopped
        networks:
            - htl-kahoot-network
        links:
            - app
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html/
            - ./nginx/conf.d/:/etc/nginx/conf.d/

    # PostgreSQL Service
    db:
        image: postgres:17
        container_name: htl-kahoot_db
        restart: unless-stopped
        networks:
            - htl-kahoot-network
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: htl-kahoot
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        volumes:
            - dbdata:/var/lib/postgresql/data/
            - ./postgres/initdb:/docker-entrypoint-initdb.d:ro
        command: postgres

    # Mailpit Service
    mailpit:
        image: axllent/mailpit
        restart: unless-stopped
        networks:
            - htl-kahoot-network
        ports:
            - "8025:8025"
            - "1025:1025"
        volumes:
            - mailpitData:/data
        environment:
            MP_MAX_MESSAGES: 5000
            MP_DATABASE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1

    # Selenium Service (Chrome) -> used for dusk testing
    selenium:
        image: selenium/standalone-chrome
        platform: linux/amd64
        ports:
            - "4444:4444"
        networks:
            - default

    # Redis Service
    redis:
        image: redis:alpine
        restart: unless-stopped
        networks:
            - htl-kahoot-network
        ports:
            - "6379:6379"
        volumes:
            - redisdata:/data

    # MinIO Service
    minio:
        image: minio/minio:latest
        restart: unless-stopped
        networks:
            - htl-kahoot-network
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        volumes:
            - minio_data:/data
        command: server /data --console-address ":9001"

    # SonarQube service

# Volumes
volumes:
    dbdata:
        driver: local
    mailpitData:
        driver: local
    redisdata:
        driver: local
    sonarqube_data:
    sonarqube_logs:
    sonarqube_extensions:
    postgres_data:
    minio_data:

networks:
    htl-kahoot-network:
